POST http://localhost:2525/imposters
content-Type: application/json

{
   "name":"Ex12",
   "port":4512,
   "protocol":"http",
   "stubs": [{
    "responses": [
      {"is": {"statusCode": 200,
          "headers": { "Content-Type": "application/json" },
          "body": { 
            "token": "Valido",
            "expires_in": "5 min"
            }
        }
      }
    ],
    "predicates": [
      {
        "deepEquals": {
          "path": "/api/auth",
          "method": "POST",
          "body": { 
            "username": "user", 
            "password": "user!" 
            }
        }
      }
    ]
  },
  {
    "responses": [
      {"is": {"statusCode": 401,
          "headers": { "Content-Type": "application/json" },
          "body": { 
            "token": "Error",
            "expires_in": "Expirado"
            }
        }
      }
    ],
    "predicates": [
      {
        "deepEquals": {
          "path": "/api/auth",
          "method": "POST",
          "body": { 
            "username": "oser", 
            "password": "oser?" 
            }
        }
      }
    ]
  }
]
}



###

POST http://localhost:4512/api/auth
Content-Type: application/json

{ 
    "username": "user", 
    "password": "user!" 
}

###

POST http://localhost:4512/api/auth
Content-Type: application/json

{ 
    "username": "oser", 
    "password": "oser?" 
}

