POST http://localhost:2525/Imposters
content-Type: application/json

{
 "port": 4545,
  "protocol": "http",
  "stubs": [{
    "responses": [
      { "is": { "statusCode": 200 }}
    ],
    "predicates": [{
      "and": [
        {
          "equals": {
            "path": "/test",
            "method": "POST",
            "headers": { "Content-Type": "application/json" }
          }
        },
        {
          "not": {
            "contains": { "body": "requiredField" },
            "caseSensitive": true
          }
        }
      ]
    }]
  }]
}

###
POST http://localhost:4545/test
content-Type: application/json

{"optionalField": true}

###
POST http://localhost:2525/Imposters
content-Type: application/json

{
 "name": "API 2",  
 "port": 4546,
  "protocol": "http",
  "stubs": [{
    "responses": [
      { "is": { "statusCode": 200,
                "body":{"Marca":"BMW",
                        "Modelo":"M3"}
            }
      }
    ],
    "predicates": [{
      "and": [
        {
          "equals": {
            "path": "/test",
            "method": "POST",
            "headers": { "Content-Type": "application/json" }
          }
        },
        {
          "not": {
            "contains": { "body": "requiredField" },
            "caseSensitive": true
          }
        }
      ]
    }]
  }]
}

### 
Post  http://localhost:4546/test
content-Type: application/json

{"optionalField": true}