POST http://localhost:2525/imposters
Content-Type: application/json

{
  "name":"Exercicio3",
  "port":4523,
  "protocol":"http",
  "stubs":[
    {
      "responses":[{
        "is":{
          "statusCode":400,
          "headers":{"Content-Type":"application/json"},
          "body":{"error":"data de checkout invalida, n pode ser anterior ao checkin"}
        }
      }],
      "predicates":[
        {"equals":{"path":"/api/reservas","method":"POST"}},
        {"equals":{"body":{"checkout":"2026-06-15"}}}
      ]
    },
    {
      "responses":[{
        "is":{
          "statusCode":409,
          "headers":{"Content-Type":"application/json"},
          "body":{"error":"sem disponibilidade"}
        }
      }],
      "predicates":[
        {"equals":{"path":"/api/reservas","method":"POST"}},
        {"equals":{"body":{"tipo_quarto":"suite presidencial"}}}
      ]
    },
    {
      "responses":[{
        "is":{
          "statusCode":201,
          "headers":{"Content-Type":"application/json"},
          "body":{"mensagem":"reserva criada","id":103}
        }
      }],
      "predicates":[
        {"equals":{"path":"/api/reservas","method":"POST"}}
      ]
    },
    {
      "responses":[{
        "is":{
          "statusCode":200,
          "headers":{"Content-Type":"application/json"},
          "body":[
            {"id":1,"cliente":"ana","checkin":"2026-07-20","checkout":"2026-07-25","tipo_quarto":"standard"},
            {"id":2,"cliente":"salvador","checkin":"2026-05-01","checkout":"2026-05-05","tipo_quarto": "duplo"}
          ]
        }
      }],
      "predicates":[
        {"equals":{"path":"/api/reservas","method":"GET"}}
      ]
    },
    {
      "responses":[{
        "is":{
          "statusCode":400,
          "headers":{"Content-Type":"application/json"},
          "body":{"erro":"alteracao n permitida, prazo limite de 24h antes do checkin ultrapassado."}
        }
      }],
      "predicates":[
        {"equals":{"path":"/api/reservas/2","method":"PUT"}}
      ]
    },
    {
      "responses":[{
        "is":{
          "statusCode":200,
          "headers":{"Content-Type":"application/json"},
          "body":{"mensagem":"reserva altereda"}
        }
      }],
      "predicates":[
        {"equals":{"path":"/api/reservas/1","method":"PUT"}}
      ]
    },
    {
      "responses":[{
        "is":{
          "statusCode":400,
          "headers":{"Content-Type":"application/json"},
          "body":{"erro":"n e permitido cancelar uma reserva apos a data de checkin"}
        }
      }],
      "predicates":[
        {"equals":{"path":"/api/reservas/2","method":"DELETE"}}
      ]
    },
    {
      "responses":[{
        "is":{
          "statusCode":200,
          "headers":{"Content-Type":"application/json"},
          "body":{"mensagem":"reserva cancelada"}
        }
      }],
      "predicates":[
        {"equals":{"path":"/api/reservas/1","method":"DELETE"}}
      ]
    }
  ]
}


###
GET http://localhost:4523/api/reservas
Content-Type: application/json


###
POST http://localhost:4523/api/reservas
Content-Type: application/json

{
  "cliente":"bruno",
  "checkin":"2026-06-20",
  "checkout":"2026-06-15",
  "tipo_quarto":"standard"
}


###
POST http://localhost:4523/api/reservas
Content-Type: application/json

{
  "cliente":"diana",
  "checkin":"2026-07-01",
  "checkout":"2026-07-05",
  "tipo_quarto":"suite presidencial"
}

###
POST http://localhost:4523/api/reservas
Content-Type: application/json

{
  "cliente":"diana",
  "checkin":"2026-07-01",
  "checkout":"2026-07-05",
  "tipo_quarto":"standard"
}


###
PUT http://localhost:4523/api/reservas/1
Content-Type: application/json

{
  "tipo_quarto":"duplo"
}


###
PUT http://localhost:4523/api/reservas/2
Content-Type: application/json

{
  "tipo_quarto":"standard"
}


###
DELETE http://localhost:4523/api/reservas/2
Content-Type: application/json


###
DELETE http://localhost:4523/api/reservas/1
Content-Type: application/json