POST http://localhost:2525/imposters
Content-Type: application/json

{
  "name":"Exercicio4",
  "port":4524,
  "protocol":"http",
  "stubs":[
    {
      "responses":[{
        "is":{
          "statusCode":400,
          "headers":{"Content-Type": "application/json"},
          "body":{"erro": "dados obrigatorios em falta, requer cliente, livro_id e data_emprestimo."}
        }
      }],
      "predicates":[
        {"equals":{"path":"/api/emprestimos", "method": "POST"}},
        {"exists":{"body":{"cliente": false}}}
      ]
    },
    {
      "responses":[{
        "is":{
          "statusCode":409,
          "headers":{"Content-Type": "application/json"},
          "body":{"erro": "o livro solicitado ja esta emprestado"}
        }
      }],
      "predicates":[
        {"equals":{"path":"/api/emprestimos","method":"POST"}},
        {"equals":{"body":{"livro_id": 99}}}
      ]
    },
    {
      "responses":[{
        "is":{
          "statusCode":201,
          "headers":{"Content-Type":"application/json"},
          "body":{ "mensagem":"emprestimo registado","emprestimo_id": 501,"livro_id": 1,"cliente":"carlos"}
        }
      }],
      "predicates":[
        {"equals":{"path":"/api/emprestimos","method":"POST"}}
      ]
    },
    {
      "responses":[{
        "is":{
          "statusCode":404,
          "headers":{"Content-Type": "application/json"},
          "body":{"erro":"emprestimo n encontrado ou ja devolvid"}
        }
      }],
      "predicates":[
        {"equals":{"path":"/api/emprestimos/99/devolucao","method":"PUT"}}
      ]
    },
    {
      "responses":[{
        "is":{
          "statusCode":200,
          "headers":{"Content-Type":"application/json"},
          "body":{"mensagem":"livro devolvido e disponivel"}
        }
      }],
      "predicates":[
        {"equals":{"path":"/api/emprestimos/501/devolucao","method":"PUT"}}
      ]
    },
    {
      "responses":[{
        "is":{
          "statusCode":409,
          "headers":{"Content-Type": "application/json"},
          "body":{"erro": "n e possivel remover o livro, ha emprstimos ativos associados"}
        }
      }],
      "predicates":[
        {"equals":{"path":"/api/livros/2","method":"DELETE"}}
      ]
    },
    {
      "responses":[{
        "is":{
          "statusCode":200,
          "headers":{"Content-Type":"application/json"},
          "body":{"mensagem":"livro removido do catalogo"}
        }
      }],
      "predicates":[
        {"equals":{"path":"/api/livros/1","method":"DELETE"}}
      ]
    },
    {
      "responses":[{
        "is":{
          "statusCode":200,
          "headers":{"Content-Type":"application/json"},
          "body":{ "id":1,"titulo":"o principezinho","autor":"antoine de saint-exupery","disponivel":true}
        }
      }],
      "predicates":[
        {"equals":{"path":"/api/livros/1","method":"GET"}}
      ]
    },
    {
      "responses":[{
        "is":{
          "statusCode":200,
          "headers":{"Content-Type":"application/json"},
          "body":[
            {"id":1,"titulo":"o principezinho","autor":"antoine de saint-exupery","disponivel":true},
            {"id":2,"titulo":"1984","autor":"george orwell","disponivel": false },
            {"id":3,"titulo":"memorial do convento","autor":"jose saramago","disponivel":true}
          ]
        }
      }],
      "predicates":[
        {"equals":{"path":"/api/livros","method":"GET"}}
      ]
    }
  ]
}

###
GET http://localhost:4524/api/livros
Content-Type: application/json

###
GET http://localhost:4524/api/livros/1
Content-Type: application/json

###
POST http://localhost:4524/api/emprestimos
Content-Type: application/json

{
  "livro_id":1,
  "data_emprestimo":"2026-06-16"
}

###
POST http://localhost:4524/api/emprestimos
Content-Type: application/json

{
  "cliente":"rita",
  "livro_id":99,
  "data_emprestimo":"2026-06-16"
}

###
POST http://localhost:4524/api/emprestimos
Content-Type: application/json

{
  "cliente":"carlos",
  "livro_id":1,
  "data_emprestimo":"2026-06-16"
}

###
PUT http://localhost:4524/api/emprestimos/99/devolucao
Content-Type: application/json

###
PUT http://localhost:4524/api/emprestimos/501/devolucao
Content-Type: application/json

###
DELETE http://localhost:4524/api/livros/2
Content-Type: application/json

###
DELETE http://localhost:4524/api/livros/1
Content-Type: application/json