POST http://localhost:2525/imposters
Content-Type: application/json

{
  "name":"Exercicio7",
  "port":4527,
  "protocol":"http",
  "stubs":[
    {
      "responses":[{
        "is":{
          "statusCode":400,
          "headers":{"Content-Type": "application/json"},
          "body":{"erro":"falta de dados, requer cliente_id, produto e quantidade."}
        }
      }],
      "predicates":[
        {"equals":{"path":"/api/pedidos","method":"POST"}},
        {"or":[
          {"exists":{"body":{"cliente_id":false}}},
          {"exists":{"body":{"produto":false}}},
          {"exists":{"body":{"quantidade":false}}}
        ]}
      ]
    },
    {
      "responses":[{
        "is":{
          "statusCode":404,
          "headers":{"Content-Type":"application/json"},
          "body":{"erro":"cliente n encontrado no sistema."}
        }
      }],
      "predicates":[
        {"equals":{"path":"/api/pedidos","method":"POST"}},
        {"deepEquals":{"body":{"cliente_id":99}}}
      ]
    },
    {
      "responses":[{
        "is":{
          "statusCode":400,
          "headers":{"Content-Type":"application/json"},
          "body":{"erro":"quantidade invalida, deve ser maior que zero."}
        }
      }],
      "predicates":[
        {"equals":{"path":"/api/pedidos","method":"POST"}},
        {"deepEquals":{"body":{"quantidade":0}}}
      ]
    },
    {
      "responses":[{
        "is":{
          "statusCode":201,
          "headers":{"Content-Type":"application/json"},
          "body":{
            "mensagem":"pedido criado",
            "pedido_id":501,
            "cliente_id":1,
            "produto":"rato sem fio",
            "quantidade":2,
            "estado":"em processamento"
          }
        }
      }],
      "predicates":[
        {"equals":{"path":"/api/pedidos","method":"POST"}}
      ]
    },
    {
      "responses":[{
        "is":{
          "statusCode":200,
          "headers":{"Content-Type":"application/json"},
          "body":{
            "mensagem":"estado do pedido atualizado",
            "pedido_id":1,
            "novo_estado":"enviado"
          }
        }
      }],
      "predicates":[
        {"equals":{"path":"/api/pedidos/1","method":"PUT"}},
        {"or":[
          {"deepEquals":{"body":{"estado":"em processamento"}}},
          {"deepEquals":{"body":{"estado":"enviado"}}},
          {"deepEquals":{"body":{"estado":"entregue"}}}
        ]}
      ]
    },
    {
      "responses":[{
        "is":{
          "statusCode": 400,
          "headers":{"Content-Type":"application/json"},
          "body":{"erro":"estado invalido, permitido apenas: 'em processamento', 'enviado' ou 'entregue'."}
        }
      }],
      "predicates":[
        {"equals":{"path":"/api/pedidos/1","method":"PUT"}}
      ]
    },
    {
      "responses":[{
        "is":{
          "statusCode":409,
          "headers":{"Content-Type":"application/json"},
          "body":{"erro":"n e possivel cancelar o pedido, o estado atual n permite o cancelamento."}
        }
      }],
      "predicates":[
        {"equals":{"path":"/api/pedidos/2","method":"DELETE"}}
      ]
    },
    {
      "responses":[{
        "is":{
          "statusCode":200,
          "headers":{"Content-Type":"application/json"},
          "body":{"mensagem":"pedido cancelado."}
        }
      }],
      "predicates":[
        {"equals":{"path":"/api/pedidos/1","method":"DELETE"}}
      ]
    },
    {
      "responses":[{
        "is":{
          "statusCode":200,
          "headers":{"Content-Type":"application/json"},
          "body":[
            {"pedido_id":1,"produto":"teclado","quantidade":1,"estado":"em processamento"},
            {"pedido_id":2,"produto":"monitor","quantidade":2,"estado":"enviado"}
          ]
        }
      }],
      "predicates":[
        {"equals":{"path":"/api/clientes/1/pedidos","method":"GET"}}
      ]
    },
    {
      "responses":[{
        "is":{
          "statusCode":201,
          "headers":{"Content-Type":"application/json"},
          "body" {
            "mensagem":"cliente add",
            "cliente_id":4,
            "nome":"lucas"
          }
        }
      }],
      "predicates":[
        {"equals":{"path":"/api/clientes","method":"POST"}}
      ]
    },
    {
      "responses":[{
        "is":{
          "statusCode":200,
          "headers":{"Content-Type":"application/json"},
          "body":[
            {"id":1,"nome":"maria"},
            {"id":2,"nome":"joao"},
            {"id":3,"nome":"julia"}
          ]
        }
      }],
      "predicates":[
        {"equals":{"path":"/api/clientes","method":"GET"}}
      ]
    }
  ]
}

###
GET http://localhost:4527/api/clientes
Content-Type: application/json

###
POST http://localhost:4527/api/clientes
Content-Type: application/json

{
  "nome":"lucas"
}

###
GET http://localhost:4527/api/clientes/1/pedidos
Content-Type: application/json

###
POST http://localhost:4527/api/pedidos
Content-Type: application/json

{
  "cliente_id":1,
  "quantidade":2
}

###
POST http://localhost:4527/api/pedidos
Content-Type: application/json

{
  "cliente_id":99,
  "produto":"rato sem fio",
  "quantidade":1
}

###
POST http://localhost:4527/api/pedidos
Content-Type: application/json

{
  "cliente_id":1,
  "produto":"rato sem fios",
  "quantidade":0
}

###
POST http://localhost:4527/api/pedidos
Content-Type: application/json

{
  "cliente_id":1,
  "produto":"rato sem fios",
  "quantidade":2
}

###
PUT http://localhost:4527/api/pedidos/1
Content-Type: application/json

{
  "estado":"cancelado"
}

###
PUT http://localhost:4527/api/pedidos/1
Content-Type: application/json

{
  "estado":"enviado"
}

###
DELETE http://localhost:4527/api/pedidos/2
Content-Type: application/json

###
DELETE http://localhost:4527/api/pedidos/1
Content-Type: application/json