POST http://localhost:2525/imposters
Content-Type: application/json

{
  "name": "Ex14",
  "port": 4514,
  "protocol": "http",
  "stubs": [
    {
      "responses": [
        {"is": {"statusCode": 415,
            "headers": { "Content-Type": "application/json" },
            "body": {
              "error": "Error",
              "mensagem": " É obrigatório o Content-Type: application/json"
            }
          }
        }
      ],
      "predicates": [
        {
          "equals": { 
            "method": "POST" 
            },
          "not": {
            "equals": {
              "headers": { "Content-Type": "application/json" }
            }
          }
        }
      ]
    }
  ]
}

###
POST http://localhost:4514/api/login
Content-Type: text/plain

###
POST http://localhost:4514/api/qualquer
