POST http://localhost:2525/imposters
Content-Type: application/json

{
    "name":"Ex1",
    "port":4551,
    "protocol":"http",
    "stubs": [{
        "responses":[
            {"is": {"statuscode": 200,
            "body":{
                "Marca":[
                    "Porche",
                    "Fiat",
                    "BWN",
                    "Mercedes",
                    "Dacia"]
             }
                                    }}
        ],
        "predicates":[{
            "and":[
                {
                    "equals":{
                        "path":"/api/marcas",
                        "method":"GET",
                        "headers": { "Content-Type": "application/json" }
                    }
                },
                {
                    "not":{
                        "contains":{"body": "requiredField" },
                        "caseSensitive": true
                    }
                }
            ]


        }]
    }]
}

###

GET http://localhost:4551/api/marcas
Content-Type: application/json