POST http://localhost:2525/imposters
Content-Type: application/json

{
    "name":"Ex2",
    "port":4552,
    "protocol":"http",
    "stubs":[{
        "responses":[
            {"is": {"statuscode":200,
                    "body":{"Marca": "Toyota",
                            "id":1,
                            "preco":300                    }
                                    }}
        ],
        "predicates":[{
            "and":[
                {
                    "equals":{
                        "path":"/api/cars",
                        "method":"GET",
                        "headers": { "Content-Type": "application/json" },
                        "query":{
                            "Marca":"Toyota"
                        }
                    }
                },
                {
                    "not":{
                        "contains":{"body": "requiredField" },
                        "caseSensitive": true
                    }
                }
            ]

        }]
    }]
}

###

GET http://localhost:4552/api/cars?Marca=Toyota
Content-Type: application/json

###

DELETE http://localhost:2525/imposters/4552
Content-Type: application/json