POST http://localhost:2525/imposters
Content-Type: application/json

{
    "name":"Ex8",
    "port":4508,
    "protocol":"http",
    "stubs":[{
        "responses":[
            {"is":{"statusCode":400,
                "headers":{"Content-Type": "application/json" },
                "body":{
                    "status":"missing_field"
                }
            }}
        ],
        "predicates":[
            {
                "equals":{
                    "path":"/api/temperature",
                    "method":"POST"
                }
            },
            {
                "not":{
                    "contains":{
                        "body":{
                            "value": 13
                        }
                    }
                }
            }
        ]
    }]
}

###

POST http://localhost:4508/api/temperature
Content-Type: application/json

{
    "value": "string"
}

###
DELETE http://localhost:2525/imposters/4508
Content-Type: application/json